#!/bin/bash

if [ $# != 1 ]; then
    exit
fi

if [ $1 = "get_sunrise_time" ]; then
    time=$(grep "yweather:astronomy" ~/.cache/weather.xml | grep -o "sunrise=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*")
    echo ${time:0:-3}
elif [ $1 = "get_sunset_time" ]; then
    time=$(grep "yweather:astronomy" ~/.cache/weather.xml | grep -o "sunset=\"[^\"]*\"" | grep -o "\"[^\"]*\"" | grep -o "[^\"]*")
    hour=${time:0:1}
    eutime=${time:1:-2}
    echo $((hour+12))$eutime
elif [ $1 = "get_weather_data" ]; then
    curl -s "http://weather.yahooapis.com/forecastrss?w=796597&u=c" -o ~/.cache/weather.xml
else
    exit
fi
